services:
  api:
    extends:
      file: ./apps/api/docker-compose.yml
      service: api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
  db:
    extends:
      file: ./apps/api/docker-compose.yml
      service: db
  web:
    extends:
      file: apps/web/docker-compose.yml
      service: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
